# https://golangci-lint.run/usage/quick-start/
run:
  timeout: 10m
  go: '1.21'

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - errcheck
    - exportloopref
    - goimports
    # only minor issues
    # - errorlint
    # seems to have bugs in recent version, also slow
    # - gci
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unparam
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/xiexianbin/go-grpc-demo
  gosec:
    includes:
      - G304
      - G307
    # excludes:
      # G402: TLS InsecureSkipVerify set true
      # - G402
      # G601: Implicit memory aliasing in for loop.
      # - G601

issues:
  exclude:
    # SA1019: otelgrpc.UnaryClientInterceptor is deprecated: Use [NewClientHandler] instead.
    - SA1019
