name: proto-pr

on:
  pull_request:
  merge_group:
    branches:
    - main

jobs:
  build:
    name: Proto PR Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: bufbuild/buf-setup-action@v1.33.0

      - name: version
        run: buf --version

      - name: Format
        run: buf format --diff --exit-code

      - name: Generate
        run:
          make proto/generate && git diff --exit-code  # ':!ui/packages/app/web/public/keep.go'

      - uses: bufbuild/buf-lint-action@06f9dd823d873146471cfaaf108a993fe00e5325 # v1.1.1
        with:
          input: 'proto'

      - uses: bufbuild/buf-breaking-action@c57b3d842a5c3f3b454756ef65305a50a587c5ba # v1.1.4
        with:
          input: 'proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=proto'
